# Generated by Django 2.1.5 on 2022-09-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='first name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('nick', models.CharField(blank=True, max_length=30, verbose_name='nick')),
                ('birth', models.DateField(verbose_name='birth')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img_author', verbose_name='avatar')),
                ('descripcion', models.CharField(max_length=120, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'blog authors',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitle')),
                ('content', models.TextField(blank=True, max_length=30, verbose_name='content')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_blog', verbose_name='image')),
                ('category', models.CharField(choices=[('0', 'Enterprise'), ('1', 'Education'), ('2', 'Security'), ('3', 'Community'), ('4', 'Programing')], max_length=1, verbose_name='category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'published Blog',
                'ordering': ['-id'],
            },
        ),
    ]
